### PR TITLE
Fix backend service name/port definition

### PR DESCRIPTION
**Pull request by DMatiushin**
Migration description
https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/concepts/ingress-versions/#ingress-class

### CODE REVIEW

**Review by KoopeY — APPROVED** [review]

**Comment by voborgus** [comment]
Please bump version in Chart.yml and values.yml

**Comment by DMatiushin** [comment]
> Please bump version in Chart.yml and values.yml

I suggest to keep same version to avoid problems with 1.0.4

**Comment by voborgus** [comment]
1.0.4 version not exists since the build was broken :) Lets pull updates from master branch and bump to 4.0.1

**Review by voborgus — APPROVED** [review]
thanks!

**Pull request merged**
